version: '2'
services:
    pagolinea-app:
        image: pagolinea
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://pagolinea-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pagolinea-mssql:
        extends:
            file: mssql.yml
            service: pagolinea-mssql
